### ISSUE TITLE
Enabling object cache breaks wordpress.

### ISSUE THREAD

**Issue by dreaddymck** [tillkruss/redis-cache#68]
Update redis plugin Version 1.3.7 . 
Activate. 
Site unavailable.

`[Thu Mar 22 15:45:00.200457 2018] [php7:error] [pid 13828] [client 192.168.0.100:52850] PHP Fatal error:  Uncaught Error: Class 'Predis\\Configuration\\ConnectionFactoryOption' not found in /home/user/Projects/wordpress.site.com/wp-content/plugins/redis-cache/includes/predis.php:9610\nStack trace:\n#0 /home/user/Projects/wordpress.site.com/wp-content/plugins/redis-cache/includes/predis.php(9665): Predis\\Configuration\\Options->getDefault('connections')\n#1 /home/user/Projects/wordpress.site.com/wp-content/plugins/redis-cache/includes/predis.php(8863): Predis\\Configuration\\Options->__get('connections')\n#2 /home/user/Projects/wordpress.site.com/wp-content/plugins/redis-cache/includes/predis.php(8804): Predis\\Client->createConnection(Array)\n#3 /home/user/Projects/wordpress.site.com/wp-content/object-cache.php(488): Predis\\Client->__construct(Array, Array)\n#4 /home/user/Projects/wordpress.site.com/wp-content/object-cache.php(183): WP_Object_Cache->__construct()\n#5 /home/user/Projects/wordpress.site.com/wp-includes/load.php(516): wp_cache_init()\n#6 /home/user in /home/user/Projects/wordpress.site.com/wp-content/plugins/redis-cache/includes/predis.php on line 9610`

**Comment by tillkruss** [comment]
See https://github.com/nrk/predis/issues/413.

**Comment by tillkruss** [comment]
@dreaddymck: Could you try downloading `dev-master` and see if that works for you? I'm now including the full Predis library since the single file version isn't supported anymore.

**Comment by negrusti** [comment]
Meanwhile is there a way to globally disable automatic WordPress updates for the plugin - I have several thousands WordPress sites with the plugin installed, and not all can be easily accessed. My worst nightmare  right now is they will start going down at any moment

**Comment by negrusti** [comment]
there is no dev-master branch?
from master:
```
Warning: require_once(/home/makel1/public_html/wp-content/plugins/redis-cache/includes/predis.php): failed to open stream: No such file or directory in /home/makel1/public_html/wp-content/plugins/redis-cache/includes/servers-list.php on line 50
Fatal error: require_once(): Failed opening required '/home/makel1/public_html/wp-content/plugins/redis-cache/includes/predis.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/makel1/public_html/wp-content/plugins/redis-cache/includes/servers-list.php on line 50
```

**Comment by nechry** [comment]
Hi, I get same issue, is a way to uninstall the plugin ?
I try wp plugin uninstall redis-cache, but I get
```
PHP Fatal error:  Uncaught Error: Class 'Predis\Configuration\ConnectionFactoryOption' not found in /var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php:9610
Stack trace:
#0 /var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php(9665): Predis\Configuration\Options->getDefault('connections')
#1 /var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php(8863): Predis\Configuration\Options->__get('connections')
#2 /var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php(8804): Predis\Client->createConnection(Array)
#3 /var/www/myweb/wp-content/object-cache.php(488): Predis\Client->__construct(Array, Array)
#4 /var/www/myweb/wp-content/object-cache.php(183): WP_Object_Cache->__construct()
#5 /var/www/myweb/wp-includes/load.php(516): wp_cache_init()
#6 /var/www/myweb/wp-settings.php(113): wp_start_object_cache()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1174): requir in /var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php on line 9610
Fatal error: Uncaught Error: Class 'Predis\Configuration\ConnectionFactoryOption' not found in /var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php:9610
Stack trace:
#0 /var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php(9665): Predis\Configuration\Options->getDefault('connections')
#1 /var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php(8863): Predis\Configuration\Options->__get('connections')
#2 /var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php(8804): Predis\Client->createConnection(Array)
#3 /var/www/myweb/wp-content/object-cache.php(488): Predis\Client->__construct(Array, Array)
#4 /var/www/myweb/wp-content/object-cache.php(183): WP_Object_Cache->__construct()
#5 /var/www/myweb/wp-includes/load.php(516): wp_cache_init()
#6 /var/www/myweb/wp-settings.php(113): wp_start_object_cache()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1174): requir in /var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php on line 9610
```

**Comment by dreaddymck** [comment]
```
git clone https://github.com/tillkruss/redis-cache/archive/master.zip
Cloning into 'master.zip'...
remote: Not Found
fatal: repository 'https://github.com/tillkruss/redis-cache/archive/master.zip/' not found
```
use:
`wget https://github.com/tillkruss/redis-cache/archive/master.zip`

Debug output below
enabling plugin
```
[Fri Mar 23 10:40:36.583091 2018] [php7:warn] [pid 23123] [client 192.168.0.100:46566] PHP Warning:  require_once(/home/dreaddy/Projects/wordpress.dreaddymck.com/wp-content/plugins/redis-cache-master/includes/predis.php): failed to open stream: No such file or directory in /home/dreaddy/Projects/wordpress.dreaddymck.com/wp-content/plugins/redis-cache-master/includes/servers-list.php on line 50
[Fri Mar 23 10:40:36.583145 2018] [php7:error] [pid 23123] [client 192.168.0.100:46566] PHP Fatal error:  require_once(): Failed opening required '/home/dreaddy/Projects/wordpress.dreaddymck.com/wp-content/plugins/redis-cache-master/includes/predis.php' (include_path='.:/usr/share/php') in /home/dreaddy/Projects/wordpress.dreaddymck.com/wp-content/plugins/redis-cache-master/includes/servers-list.php on line 50

```
Activating plugin

```
[Fri Mar 23 10:40:52.915269 2018] [php7:warn] [pid 9406] [client 192.168.0.100:46768] PHP Warning:  require_once(/home/dreaddy/Projects/wordpress.dreaddymck.com/wp-content/plugins/redis-cache/includes/predis/autoload.php): failed to open stream: No such file or directory in /home/dreaddy/Projects/wordpress.dreaddymck.com/wp-content/object-cache.php on line 462, referer: http://192.168.0.102/dreaddymck.com/wp-admin/options-general.php?page=redis-cache
[Fri Mar 23 10:40:52.915403 2018] [php7:error] [pid 9406] [client 192.168.0.100:46768] PHP Fatal error:  require_once(): Failed opening required '/home/dreaddy/Projects/wordpress.dreaddymck.com/wp-content/plugins/redis-cache/includes/predis/autoload.php' (include_path='.:/usr/share/php') in /home/dreaddy/Projects/wordpress.dreaddymck.com/wp-content/object-cache.php on line 462, referer: http://192.168.0.102/dreaddymck.com/wp-admin/options-general.php?page=redis-cache

```

**Comment by tillkruss** [comment]
Fixed in 1.3.8.

**Comment by tillkruss** [comment]
If you have trouble upgrading, be sure to delete your `object-cache.php` dropin.

**Comment by nechry** [comment]
I updated but still get the issue

PHP Warning:  require_once(/var/www/nechry-automation.ch/wp-content/plugins/redis-cache/includes/predis.php): failed to open stream: No such file or directory in /var/www/myweb/wp-content/object-cache.php on line 462
Warning: require_once(/var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php): failed to open stream: No such file or directory in /var/www/myweb/wp-content/object-cache.php on line 462
PHP Fatal error:  require_once(): Failed opening required '/var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php' (include_path='phar:///usr/local/bin/wp/vendor/phpunit/php-token-stream:phar:///usr/local/bin/wp/vendor/phpunit/phpunit-mock-objects:phar:///usr/local/bin/wp/vendor/phpunit/php-code-coverage:phar:///usr/local/bin/wp/vendor/phpunit/phpunit:phar:///usr/local/bin/wp/vendor/symfony/yaml:.:/usr/share/php') in /var/www/myweb/wp-content/object-cache.php on line 462
Fatal error: require_once(): Failed opening required '/var/www/myweb/wp-content/plugins/redis-cache/includes/predis.php' (include_path='phar:///usr/local/bin/wp/vendor/phpunit/php-token-stream:phar:///usr/local/bin/wp/vendor/phpunit/phpunit-mock-objects:phar:///usr/local/bin/wp/vendor/phpunit/php-code-coverage:phar:///usr/local/bin/wp/vendor/phpunit/phpunit:phar:///usr/local/bin/wp/vendor/symfony/yaml:.:/usr/share/php') in /var/www/myweb/wp-content/object-cache.php on line 462

**Comment by tillkruss** [comment]
See the comment above.

**Comment by dreaddymck** [comment]
Version 1.3.8 Confirmed working.  Thank you  @tillkruss.

Closing issue.
